// <auto-generated />
// Design-time stub to surface Neemle.XJson.Generated.Json during IntelliSense.
// Included only when DesignTimeBuild is true; not part of runtime builds.
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Neemle.XJson.Generated;

public static class Json
{
    private const string _msg = "XJson design-time stub. Build normally to get the generated implementation.";

    public static string Encode<T>(T value) => throw new NotSupportedException(_msg);
    public static string Encode<T>(T value, JsonSerializerOptions? options) => throw new NotSupportedException(_msg);
    public static string Encode<T>(T value, JsonSourceGenerationOptionsAttribute? genOptions) => throw new NotSupportedException(_msg);

    public static T Decode<T>(string json) => throw new NotSupportedException(_msg);
    public static T Decode<T>(string json, JsonSerializerOptions? options) => throw new NotSupportedException(_msg);
    public static T Decode<T>(string json, JsonSourceGenerationOptionsAttribute? genOptions) => throw new NotSupportedException(_msg);

    public static bool Validate<T>(string json, out T? value, out string? error) => throw new NotSupportedException(_msg);
    public static bool Validate<T>(string json, out T? value, out string? error, JsonSerializerOptions? options) => throw new NotSupportedException(_msg);
    public static bool Validate<T>(string json, out T? value, out string? error, JsonSourceGenerationOptionsAttribute? genOptions) => throw new NotSupportedException(_msg);
}
