using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Neemle.XJson.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class XJsonGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Neemle.XJson.Abstractions.XJsonAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var markedTypes = context.SyntaxProvider.ForAttributeWithMetadataName<INamedTypeSymbol>(
            AttributeMetadataName,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol!);

        var collected = markedTypes
            .Where(static t => t is { IsAbstract: false, DeclaredAccessibility: Accessibility.Public })
            .Collect();

        context.RegisterSourceOutput(collected, EmitContext);
    }

    private static void EmitContext(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
        {
            return;
        }

        var types = candidates
            .Distinct(NamedTypeSymbolComparer.Instance)
            .ToImmutableArray();
        if (types.Length == 0)
        {
            return;
        }

        var source = BuildSource(types);
        context.AddSource("XJsonContext.g.cs", source);
    }

    private static string BuildSource(ImmutableArray<INamedTypeSymbol> types)
    {
        var format = new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace Neemle.XJson.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class XJsonGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly Dictionary<Type, JsonConverter> Converters = CreateConverters();");
        sb.AppendLine();
        sb.AppendLine("    private static Dictionary<Type, JsonConverter> CreateConverters()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new Dictionary<Type, JsonConverter>");
        sb.AppendLine("        {");
        foreach (var type in types)
        {
            sb.AppendLine($"            {{ typeof({type.ToDisplayString(format)}), new {GetConverterName(type)}() }},");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"Converters are reflection-free.\")]");
        sb.AppendLine("    public static string Serialize<T>(T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        var converter = Resolve<T>();");
        sb.AppendLine("        var buffer = new ArrayBufferWriter<byte>();");
        sb.AppendLine("        using var writer = new Utf8JsonWriter(buffer);");
        sb.AppendLine("        converter.Write(writer, value!, new JsonSerializerOptions());");
        sb.AppendLine("        writer.Flush();");
        sb.AppendLine("        return System.Text.Encoding.UTF8.GetString(buffer.WrittenSpan);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    [UnconditionalSuppressMessage(\"Trimming\", \"IL2026\", Justification = \"Converters are reflection-free.\")]");
        sb.AppendLine("    public static T? Deserialize<T>(string json)");
        sb.AppendLine("    {");
        sb.AppendLine("        var converter = Resolve<T>();");
        sb.AppendLine("        var reader = new Utf8JsonReader(System.Text.Encoding.UTF8.GetBytes(json));");
        sb.AppendLine("        if (!reader.Read()) throw new JsonException(\"Empty payload.\");");
        sb.AppendLine("        return converter.Read(ref reader, typeof(T), new JsonSerializerOptions());");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static JsonConverter<T> Resolve<T>()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (Converters.TryGetValue(typeof(T), out var converter))");
        sb.AppendLine("        {");
        sb.AppendLine("            return (JsonConverter<T>)converter;");
        sb.AppendLine("        }");
        sb.AppendLine("        throw new NotSupportedException($\"Type '{typeof(T)}' is not marked with [XJson].\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        foreach (var type in types)
        {
            AppendConverter(sb, type, format, types);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void AppendConverter(StringBuilder sb, INamedTypeSymbol type, SymbolDisplayFormat format, ImmutableArray<INamedTypeSymbol> allTypes)
    {
        var typeName = type.ToDisplayString(format);
        var converterName = GetConverterName(type);
        var properties = type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.GetMethod is not null && p.SetMethod is not null)
            .ToArray();

        sb.AppendLine($"file sealed class {converterName} : JsonConverter<{typeName}>");
        sb.AppendLine("{");
        AppendReadMethod(sb, typeName, properties, format, allTypes);
        sb.AppendLine();
        AppendWriteMethod(sb, typeName, properties, format, allTypes);
        sb.AppendLine("}");
    }

    private static void AppendWriteMethod(StringBuilder sb, string typeName, IPropertySymbol[] properties, SymbolDisplayFormat format, ImmutableArray<INamedTypeSymbol> allTypes)
    {
        sb.AppendLine("    public override void Write(Utf8JsonWriter writer, " + typeName + " value, JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteStartObject();");
        foreach (var property in properties)
        {
            var jsonName = ToJsonName(property.Name);
            sb.AppendLine($"        writer.WritePropertyName(\"{jsonName}\");");
            sb.AppendLine($"        {GetWriteExpression(property, format, allTypes)}");
        }
        sb.AppendLine("        writer.WriteEndObject();");
        sb.AppendLine("    }");
    }

    private static void AppendReadMethod(StringBuilder sb, string typeName, IPropertySymbol[] properties, SymbolDisplayFormat format, ImmutableArray<INamedTypeSymbol> allTypes)
    {
        sb.AppendLine("    public override " + typeName + " Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.TokenType != JsonTokenType.StartObject) throw new JsonException(\"Expected object start.\");");
        foreach (var property in properties)
        {
            sb.AppendLine($"        {property.Type.ToDisplayString(format)} {ToCamelCase(property.Name)}Value = default!;");
            sb.AppendLine($"        bool {ToCamelCase(property.Name)}Seen = false;");
        }
        sb.AppendLine();
        sb.AppendLine("        while (reader.Read())");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.TokenType == JsonTokenType.EndObject) break;");
        sb.AppendLine("            if (reader.TokenType != JsonTokenType.PropertyName) throw new JsonException(\"Expected property name.\");");
        sb.AppendLine("            var propName = reader.GetString();");
        sb.AppendLine("            reader.Read();");
        sb.AppendLine("            switch (propName)");
        sb.AppendLine("            {");
        foreach (var property in properties)
        {
            var jsonName = ToJsonName(property.Name);
            sb.AppendLine($"                case \"{jsonName}\":");
            sb.AppendLine($"                    {ToCamelCase(property.Name)}Value = {GetReadExpression(property, format, allTypes)};");
            sb.AppendLine($"                    {ToCamelCase(property.Name)}Seen = true;");
            sb.AppendLine("                    break;");
        }
        sb.AppendLine("                default:");
        sb.AppendLine("                    reader.Skip();");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        reader.Read();");
        sb.AppendLine();
        sb.AppendLine($"        var result = new {typeName}();");
        foreach (var property in properties)
        {
            sb.AppendLine($"        result.{property.Name} = {ToCamelCase(property.Name)}Value;");
        }
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static string GetWriteExpression(IPropertySymbol property, SymbolDisplayFormat format, ImmutableArray<INamedTypeSymbol> allTypes)
    {
        var type = property.Type;
        var typeName = type.ToDisplayString(format);

        switch (type.SpecialType)
        {
            case SpecialType.System_String:
                return $"writer.WriteStringValue(value.{property.Name});";
            case SpecialType.System_Boolean:
                return $"writer.WriteBooleanValue(value.{property.Name});";
            case SpecialType.System_Int32 or SpecialType.System_Int64 or SpecialType.System_Int16 or SpecialType.System_Byte:
                return $"writer.WriteNumberValue(value.{property.Name});";
            case SpecialType.System_UInt32 or SpecialType.System_UInt64 or SpecialType.System_UInt16 or SpecialType.System_SByte:
                return $"writer.WriteNumberValue(value.{property.Name});";
            case SpecialType.System_Single:
                return $"writer.WriteNumberValue(value.{property.Name});";
            case SpecialType.System_Double:
                return $"writer.WriteNumberValue(value.{property.Name});";
            case SpecialType.System_Decimal:
                return $"writer.WriteNumberValue(value.{property.Name});";
        }

        if (type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Guid")
            return $"writer.WriteStringValue(value.{property.Name}.ToString());";

        if (type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.DateTime")
            return $"writer.WriteStringValue(value.{property.Name}.ToString(\"O\"));";

        if (type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.TimeSpan")
            return $"writer.WriteStringValue(value.{property.Name}.ToString());";

        if (!allTypes.Any(t => SymbolEqualityComparer.Default.Equals(t, type)))
            return "throw new NotSupportedException(\"Unsupported property type for XJson; only primitives, Guid, DateTime, TimeSpan, or other [XJson] types are supported.\");";
        var converterName = GetConverterName((INamedTypeSymbol)type);
        return $"new {converterName}().Write(writer, value.{property.Name}, options);";

    }

    private static string GetReadExpression(IPropertySymbol property, SymbolDisplayFormat format, ImmutableArray<INamedTypeSymbol> allTypes)
    {
        var type = property.Type;
        var typeName = type.ToDisplayString(format);

        return type.SpecialType switch
        {
            SpecialType.System_String => "reader.GetString()!",
            SpecialType.System_Boolean => "reader.GetBoolean()",
            SpecialType.System_Int32 => "reader.GetInt32()",
            SpecialType.System_Int64 => "reader.GetInt64()",
            SpecialType.System_Int16 => "reader.GetInt16()",
            SpecialType.System_Byte => "reader.GetByte()",
            SpecialType.System_UInt32 => "reader.GetUInt32()",
            SpecialType.System_UInt64 => "reader.GetUInt64()",
            SpecialType.System_UInt16 => "reader.GetUInt16()",
            SpecialType.System_SByte => "reader.GetSByte()",
            SpecialType.System_Single => "reader.GetSingle()",
            SpecialType.System_Double => "reader.GetDouble()",
            SpecialType.System_Decimal => "reader.GetDecimal()",
            _ when type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.Guid" => "Guid.Parse(reader.GetString()!)",
            _ when type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.DateTime" => "DateTime.Parse(reader.GetString()!)",
            _ when type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.TimeSpan" => "TimeSpan.Parse(reader.GetString()!)",
            _ => allTypes.Any(t => SymbolEqualityComparer.Default.Equals(t, type))
                ? $"new {GetConverterName((INamedTypeSymbol)type)}().Read(ref reader, typeof({typeName}), options)!"
                : "throw new NotSupportedException(\"Unsupported property type for XJson; only primitives, Guid, DateTime, TimeSpan, or other [XJson] types are supported.\")"
        };
    }

    private static string GetConverterName(INamedTypeSymbol type) => $"{type.Name}XConverter";

    private static string ToJsonName(string name)
    {
        if (string.IsNullOrEmpty(name) || char.IsLower(name[0]))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string ToCamelCase(string name) => ToJsonName(name);

    private sealed class NamedTypeSymbolComparer : IEqualityComparer<INamedTypeSymbol>
    {
        public static readonly NamedTypeSymbolComparer Instance = new();

        public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y) =>
            SymbolEqualityComparer.Default.Equals(x, y);

        public int GetHashCode(INamedTypeSymbol obj) =>
            SymbolEqualityComparer.Default.GetHashCode(obj);
    }
}
