using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Neemle.XJson.Generator;

/// <summary>
/// Generates source code at compile-time for types annotated with specific attributes.
/// This generator works by analyzing the syntax tree during compilation, identifying
/// types with relevant attributes, and producing additional source code as needed.
/// </summary>
/// <remarks>
/// This source generator leverages the <see cref="IIncrementalGenerator"/> interface to
/// efficiently process syntax nodes and symbols incrementally, minimizing performance overhead.
/// The primary steps in the generation process are:
/// 1. Identifying candidate types using syntax-based heuristics.
/// 2. Extracting relevant type information for further processing.
/// 3. Generating and emitting source code based on the collected data.
/// </remarks>
/// <example>
/// This generator is intended for use in scenarios where developers need to augment
/// existing code with source-generated implementations, such as additional methods,
/// properties, or classes.
/// Note: No example usage is provided as per the instructions.
/// </example>
/// <threadsafety>
/// This class is thread-safe and designed to work efficiently in the Roslyn compilation context,
/// ensuring correctness and performance for incremental builds.
/// </threadsafety>
[Generator]
public class XJsonSourceGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the XJson source generator by setting up the syntax and compilation providers
    /// and registering the source output actions.
    /// </summary>
    /// <param name="context">The incremental generator initialization context used to configure the generator.</param> 
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all syntax nodes with attributes
        var candidateTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidate(s),
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static m => m is not null);

        var compilationAndTypes = context.CompilationProvider.Combine(candidateTypes.Collect());

        context.RegisterSourceOutput(compilationAndTypes,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidate(SyntaxNode node) =>
        node is TypeDeclarationSyntax t &&
        t.AttributeLists.Count > 0;

    private static INamedTypeSymbol? GetTypeInfo(GeneratorSyntaxContext ctx)
    {
        var typeDecl = (TypeDeclarationSyntax)ctx.Node;

        foreach (var attr in typeDecl.AttributeLists.SelectMany(a => a.Attributes))
        {
            var symbol = ctx.SemanticModel.GetSymbolInfo(attr).Symbol;
            if (symbol?.ContainingType.ToDisplayString() ==
                "Neemle.XJson.Abstractions.XJsonAttribute")
            {
                return ctx.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;
            }
        }
        return null;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> types,
        SourceProductionContext context)
    {
        if (types.IsDefaultOrEmpty)
        {
            EmitDesignTimeStub(context);
            return;
        }

        var distinctTypes = types.Distinct(NamedTypeSymbolComparer.Default).ToArray();
        if (distinctTypes.Length == 0)
        {
            EmitDesignTimeStub(context);
            return;
        }

        // ---- Generate reflection-free converters + helper ----
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("namespace Neemle.XJson.Generated;");

        // Emit helper with options and converter registration
        sb.AppendLine("public static class Json");
        sb.AppendLine("{");
        sb.AppendLine("    internal static readonly JsonSerializerOptions DefaultOptions;");
        sb.AppendLine();
        sb.AppendLine("    static Json()");
        sb.AppendLine("    {");
        sb.AppendLine("        DefaultOptions = new JsonSerializerOptions\n        {\n            WriteIndented = true,\n            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,\n            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull\n        };\n");

        // Converters are invoked directly; no registration needed.

        sb.AppendLine("    }");
        sb.AppendLine();
        // Map System.Text.Json's JsonSourceGenerationOptionsAttribute to JsonSerializerOptions
        sb.AppendLine("    private static JsonSerializerOptions From(JsonSourceGenerationOptionsAttribute? gen)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (gen is null) return DefaultOptions;");
        sb.AppendLine("        var opts = new JsonSerializerOptions(DefaultOptions);");
        sb.AppendLine("        opts.WriteIndented = gen.WriteIndented;");
        sb.AppendLine("        opts.DefaultIgnoreCondition = gen.DefaultIgnoreCondition;");
        sb.AppendLine("        opts.PropertyNamingPolicy = gen.PropertyNamingPolicy switch");
        sb.AppendLine("        {");
        sb.AppendLine("            JsonKnownNamingPolicy.Unspecified => null,");
        sb.AppendLine("            JsonKnownNamingPolicy.CamelCase => JsonNamingPolicy.CamelCase,");
#if NET8_0_OR_GREATER
        sb.AppendLine("            JsonKnownNamingPolicy.SnakeCaseLower => JsonNamingPolicy.SnakeCaseLower,");
        sb.AppendLine("            JsonKnownNamingPolicy.SnakeCaseUpper => JsonNamingPolicy.SnakeCaseUpper,");
        sb.AppendLine("            JsonKnownNamingPolicy.KebabCaseLower => JsonNamingPolicy.KebabCaseLower,");
        sb.AppendLine("            JsonKnownNamingPolicy.KebabCaseUpper => JsonNamingPolicy.KebabCaseUpper,");
#endif
        sb.AppendLine("            _ => opts.PropertyNamingPolicy");
        sb.AppendLine("        };\n        return opts;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static string Encode<T>(T value)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Encode<T>(value, (JsonSerializerOptions?)null);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static string Encode<T>(T value, JsonSourceGenerationOptionsAttribute? genOptions)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Encode<T>(value, From(genOptions));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static string Encode<T>(T value, JsonSerializerOptions? options)");
        sb.AppendLine("    {");
        sb.AppendLine("        options ??= DefaultOptions;");
        sb.AppendLine("        var buffer = new ArrayBufferWriter<byte>();");
        sb.AppendLine("        using var writer = new Utf8JsonWriter(buffer, new JsonWriterOptions { Indented = options.WriteIndented });");
        bool firstIf = true;
        foreach (var t in distinctTypes)
        {
            var fullName = ToFullyQualifiedName(t);
            var safe = MakeSafeName(fullName);
            sb.AppendLine(firstIf
                ? $"        if (typeof(T) == typeof({fullName}))"
                : $"        else if (typeof(T) == typeof({fullName}))");
            sb.AppendLine("        {");
            sb.AppendLine($"            new {safe}_Converter().Write(writer, ({fullName})(object?)value!, options);");
            sb.AppendLine("        }");
            firstIf = false;
        }
        sb.AppendLine("        else throw new NotSupportedException(\"Type is not annotated with [XJson].\");");
        sb.AppendLine("        writer.Flush();");
        sb.AppendLine("        return Encoding.UTF8.GetString(buffer.WrittenSpan);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static T Decode<T>(string json)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Decode<T>(json, (JsonSerializerOptions?)null);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static T Decode<T>(string json, JsonSourceGenerationOptionsAttribute? genOptions)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Decode<T>(json, From(genOptions));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static T Decode<T>(string json, JsonSerializerOptions? options)");
        sb.AppendLine("    {");
        sb.AppendLine("        options ??= DefaultOptions;");
        sb.AppendLine("        var bytes = Encoding.UTF8.GetBytes(json);");
        sb.AppendLine("        var reader = new Utf8JsonReader(bytes);");
        sb.AppendLine("        if (!reader.Read()) throw new JsonException(\"Empty JSON.\");");
        bool firstDecode = true;
        foreach (var t in distinctTypes)
        {
            var fullName = ToFullyQualifiedName(t);
            var safe = MakeSafeName(fullName);
            sb.AppendLine(firstDecode
                ? $"        if (typeof(T) == typeof({fullName}))"
                : $"        else if (typeof(T) == typeof({fullName}))");
            sb.AppendLine("        {");
            sb.AppendLine($"            var v = new {safe}_Converter().Read(ref reader, typeof({fullName}), options);");
            sb.AppendLine($"            return (T)(object)v!;");
            sb.AppendLine("        }");
            firstDecode = false;
        }
        sb.AppendLine("        else throw new NotSupportedException(\"Type is not annotated with [XJson].\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static bool Validate<T>(string json, out T? value, out string? error)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Validate<T>(json, out value, out error, (JsonSerializerOptions?)null);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static bool Validate<T>(string json, out T? value, out string? error, JsonSourceGenerationOptionsAttribute? genOptions)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Validate<T>(json, out value, out error, From(genOptions));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static bool Validate<T>(string json, out T? value, out string? error, JsonSerializerOptions? options)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            value = Decode<T>(json, options)!;");
        sb.AppendLine("            error = null;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (JsonException ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = default;");
        sb.AppendLine("            error = ex.Message;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = default;");
        sb.AppendLine("            error = ex.Message;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Emit converters for each [XJson] type
        var __known = new HashSet<string>();
        foreach (var t in distinctTypes)
        {
            __known.Add(ToFullyQualifiedName(t));
        }

        foreach (var type in distinctTypes)
        {
            EmitConverterForType(type, sb, __known);
            sb.AppendLine();
        }

        context.AddSource("Json.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitDesignTimeStub(SourceProductionContext context)
    {
        var stub = new StringBuilder();
        stub.AppendLine("// <auto-generated />");
        stub.AppendLine("#nullable enable");
        stub.AppendLine("using System;");
        stub.AppendLine("using System.Text.Json;");
        stub.AppendLine("using System.Text.Json.Serialization;");
        stub.AppendLine("namespace Neemle.XJson.Generated;");
        stub.AppendLine();
        stub.AppendLine("public static class Json");
        stub.AppendLine("{");
        stub.AppendLine("    private const string _msg = \"XJson design-time stub. Build with the XJson generator to get the real implementation.\";");
        stub.AppendLine("    public static string Encode<T>(T value) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static string Encode<T>(T value, JsonSerializerOptions? options) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static string Encode<T>(T value, JsonSourceGenerationOptionsAttribute? genOptions) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static T Decode<T>(string json) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static T Decode<T>(string json, JsonSerializerOptions? options) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static T Decode<T>(string json, JsonSourceGenerationOptionsAttribute? genOptions) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static bool Validate<T>(string json, out T? value, out string? error) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static bool Validate<T>(string json, out T? value, out string? error, JsonSerializerOptions? options) => throw new NotSupportedException(_msg);");
        stub.AppendLine("    public static bool Validate<T>(string json, out T? value, out string? error, JsonSourceGenerationOptionsAttribute? genOptions) => throw new NotSupportedException(_msg);");
        stub.AppendLine("}");
        context.AddSource("Json.g.cs", SourceText.From(stub.ToString(), Encoding.UTF8));
    }

    private static string ToFullyQualifiedName(INamedTypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
            SymbolDisplayMiscellaneousOptions.UseSpecialTypes));

    private static string MakeSafeName(string fullName) =>
        fullName
            .Replace("global::", string.Empty)
            .Replace("::", "_")
            .Replace('.', '_')
            .Replace('+', '_')
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace('[', '_')
            .Replace(']', '_')
            .Replace(',', '_');

    private sealed class NamedTypeSymbolComparer : IEqualityComparer<INamedTypeSymbol>
    {
        public static readonly NamedTypeSymbolComparer Default = new();

        public bool Equals(INamedTypeSymbol? x, INamedTypeSymbol? y) =>
            SymbolEqualityComparer.Default.Equals(x, y);

        public int GetHashCode(INamedTypeSymbol obj) =>
            SymbolEqualityComparer.Default.GetHashCode(obj);
    }

    private static void EmitConverterForType(INamedTypeSymbol type, StringBuilder sb, HashSet<string> known)
    {
        // Only support class/struct with public get/set properties for v1
        var fullName = ToFullyQualifiedName(type);
        var safe = MakeSafeName(fullName);

        // Collect serializable properties (public get & set, not static, not indexer)
        var props = type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && !p.IsIndexer && p.GetMethod is not null && p.SetMethod is not null &&
                        p.DeclaredAccessibility == Accessibility.Public && (p.GetMethod.DeclaredAccessibility == Accessibility.Public) && (p.SetMethod.DeclaredAccessibility == Accessibility.Public))
            .ToArray();

        // If we detect an unsupported property upfront, short-circuit with a clear throw to avoid unreachable code warnings.
        var unsupported = props.FirstOrDefault(p => !IsSupportedType(p.Type, known));
        if (unsupported is not null)
        {
            var unsupportedTypeName = GetTypeDisplayName(unsupported.Type);
            sb.AppendLine($"internal sealed class {safe}_Converter : JsonConverter<{fullName}>");
            sb.AppendLine("{");
            sb.AppendLine($"    public override void Write(Utf8JsonWriter writer, {fullName} value, JsonSerializerOptions options)");
            sb.AppendLine("    {");
            sb.AppendLine($"        throw new NotSupportedException(\"Property type not supported: {unsupportedTypeName}\");");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public override {fullName} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("    {");
            sb.AppendLine($"        throw new NotSupportedException(\"Property type not supported: {unsupportedTypeName}\");");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return;
        }

        // Converter class header
        sb.AppendLine($"internal sealed class {safe}_Converter : JsonConverter<{fullName}>");
        sb.AppendLine("{");

        // Name resolution helper: attribute name wins; then options.PropertyNamingPolicy; else CLR name
        sb.AppendLine("    private static string __ResolveName(JsonSerializerOptions options, string clrName, string? attrName) => attrName ?? options.PropertyNamingPolicy?.ConvertName(clrName) ?? clrName;");
        if (props.Length > 0) sb.AppendLine();

        // Write method
        sb.AppendLine($"    public override void Write(Utf8JsonWriter writer, {fullName} value, JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteStartObject();");
        // Resolve names once per call
        foreach (var p in props)
        {
            var attrName = GetJsonPropertyNameAttributeValue(p);
            var attrLiteral = attrName is null ? "null" : EscapeStringLiteral(attrName);
            sb.AppendLine($"        var __n_{p.Name} = __ResolveName(options, \"{p.Name}\", {attrLiteral});");
        }
        foreach (var p in props)
        {
            var pType = p.Type;
            var pTypeName = GetTypeDisplayName(pType);
            var isNullable = IsNullable(pType);
            var isRef = pType.IsReferenceType;
            EmitWriteForProperty(sb, p.Name, pType, pTypeName, isRef, isNullable, known);
        }
        sb.AppendLine("        writer.WriteEndObject();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Read method
        sb.AppendLine($"    public override {fullName} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.TokenType != JsonTokenType.StartObject) throw new JsonException(\"Expected StartObject token.\");");
        // Locals
        foreach (var p in props)
        {
            var pType = p.Type;
            var pTypeName = GetTypeDisplayName(pType);
            var localType = pType.IsReferenceType && !pTypeName.EndsWith("?") ? pTypeName + "?" : pTypeName;
            sb.AppendLine($"        {localType} __val_{p.Name} = default!;");
            sb.AppendLine($"        bool __has_{p.Name} = false;");
        }
        if (props.Length > 0) sb.AppendLine();

        // Resolve expected property names
        foreach (var p in props)
        {
            var attrName = GetJsonPropertyNameAttributeValue(p);
            var attrLiteral = attrName is null ? "null" : EscapeStringLiteral(attrName);
            sb.AppendLine($"        var __n_{p.Name} = __ResolveName(options, \"{p.Name}\", {attrLiteral});");
        }

        sb.AppendLine("        while (reader.Read())");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.TokenType == JsonTokenType.EndObject) break;");
        sb.AppendLine("            if (reader.TokenType != JsonTokenType.PropertyName) throw new JsonException(\"Expected PropertyName token.\");");

        // Generate if-else chain for properties
        bool first = true;
        foreach (var p in props)
        {
            var propName = $"__n_{p.Name}";
            var pTypeName = GetTypeDisplayName(p.Type);
            sb.AppendLine(first
                ? $"            if (reader.ValueTextEquals({propName}))"
                : $"            else if (reader.ValueTextEquals({propName}))");
            sb.AppendLine("            {");
            sb.AppendLine("                reader.Read();");
            EmitReadForProperty(sb, p.Name, p.Type, pTypeName, known);
            sb.AppendLine($"                __has_{p.Name} = true;");
            sb.AppendLine("            }");
            first = false;
        }
        sb.AppendLine(props.Length == 0 ? "            { reader.Read(); reader.Skip(); }" : "            else { reader.Read(); reader.Skip(); }");

        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        var __result = new {fullName}();");
        foreach (var p in props)
        {
            var pTypeName = GetTypeDisplayName(p.Type);
            var assignment = p.Type.IsReferenceType ? $"__val_{p.Name}!" : $"__val_{p.Name}";
            sb.AppendLine($"        if (__has_{p.Name}) __result.{p.Name} = {assignment};");
        }
        sb.AppendLine("        return __result;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitWriteForProperty(StringBuilder sb, string propName, ITypeSymbol type, string typeName, bool isRef, bool isNullable, HashSet<string> known)
    {
        // Nullable<T>
        if (!isRef && isNullable && type is INamedTypeSymbol nts && nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            var underlying = nts.TypeArguments[0];
            var underlyingName = GetTypeDisplayName(underlying);
            sb.AppendLine($"        if (value.{propName}.HasValue)");
            sb.AppendLine("        {");
            EmitWriteNonNull(sb, propName, underlying, underlyingName, known, $"value.{propName}.Value");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            if (options.DefaultIgnoreCondition != JsonIgnoreCondition.WhenWritingNull)");
            sb.AppendLine($"                writer.WriteNull(__n_{propName});");
            sb.AppendLine("        }");
            return;
        }

        if (isRef)
        {
            sb.AppendLine($"        if (value.{propName} != null)");
            sb.AppendLine("        {");
            EmitWriteNonNull(sb, propName, type, typeName, known, $"value.{propName}");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            if (options.DefaultIgnoreCondition != JsonIgnoreCondition.WhenWritingNull)");
            sb.AppendLine($"                writer.WriteNull(__n_{propName});");
            sb.AppendLine("        }");
            return;
        }

        // Non-nullable value type
        EmitWriteNonNull(sb, propName, type, typeName, known, $"value.{propName}");
    }

    private static void EmitWriteNonNull(StringBuilder sb, string propName, ITypeSymbol type, string typeName, HashSet<string> known, string valueExpr)
    {
        switch (GetPrimitiveKind(type))
        {
            case PrimitiveKind.String:
                sb.AppendLine($"            writer.WriteString(__n_{propName}, {valueExpr});");
                break;
            case PrimitiveKind.Bool:
                sb.AppendLine($"            writer.WriteBoolean(__n_{propName}, {valueExpr});");
                break;
            case PrimitiveKind.Int32:
                sb.AppendLine($"            writer.WriteNumber(__n_{propName}, {valueExpr});");
                break;
            case PrimitiveKind.Int64:
                sb.AppendLine($"            writer.WriteNumber(__n_{propName}, {valueExpr});");
                break;
            default:
                // Known complex type -> call its converter
                if (type is INamedTypeSymbol nts && known.Contains(ToFullyQualifiedName(nts)))
                {
                    var safe = MakeSafeName(GetTypeDisplayName(type));
                    sb.AppendLine($"            writer.WritePropertyName(__n_{propName});");
                    sb.AppendLine($"            new {safe}_Converter().Write(writer, {valueExpr}, options);");
                }
                else
                {
                    sb.AppendLine($"            throw new NotSupportedException(\"Property type not supported: {typeName}\");");
                }
                break;
        }
    }

    private static void EmitReadForProperty(StringBuilder sb, string propName, ITypeSymbol type, string typeName, HashSet<string> known)
    {
        switch (GetPrimitiveKind(type))
        {
            case PrimitiveKind.String:
                sb.AppendLine($"                __val_{propName} = reader.TokenType == JsonTokenType.Null ? default : reader.GetString();");
                break;
            case PrimitiveKind.Bool:
                sb.AppendLine($"                __val_{propName} = reader.GetBoolean();");
                break;
            case PrimitiveKind.Int32:
                sb.AppendLine($"                __val_{propName} = reader.GetInt32();");
                break;
            case PrimitiveKind.Int64:
                sb.AppendLine($"                __val_{propName} = reader.GetInt64();");
                break;
            default:
                if (type is INamedTypeSymbol nts && nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                {
                    var u = nts.TypeArguments[0];
                    var uName = GetTypeDisplayName(u);
                    // Nullable underlying
                    switch (GetPrimitiveKind(u))
                    {
                        case PrimitiveKind.Int32:
                            sb.AppendLine($"                __val_{propName} = reader.TokenType == JsonTokenType.Null ? default : reader.GetInt32();");
                            break;
                        case PrimitiveKind.Int64:
                            sb.AppendLine($"                __val_{propName} = reader.TokenType == JsonTokenType.Null ? default : reader.GetInt64();");
                            break;
                        case PrimitiveKind.Bool:
                            sb.AppendLine($"                __val_{propName} = reader.TokenType == JsonTokenType.Null ? default : reader.GetBoolean();");
                            break;
                        case PrimitiveKind.String:
                            sb.AppendLine($"                __val_{propName} = reader.TokenType == JsonTokenType.Null ? default : reader.GetString();");
                            break;
                        default:
                            if (u is INamedTypeSymbol unts && known.Contains(ToFullyQualifiedName(unts)))
                            {
                                var safeU = MakeSafeName(GetTypeDisplayName(u));
                                sb.AppendLine($"                __val_{propName} = reader.TokenType == JsonTokenType.Null ? default : new {safeU}_Converter().Read(ref reader, typeof({uName}), options);");
                            }
                            else
                            {
                                sb.AppendLine($"                throw new NotSupportedException(\"Property type not supported: Nullable<{uName}>\");");
                            }
                            break;
                    }
                }
                else if (type is INamedTypeSymbol cts && known.Contains(ToFullyQualifiedName(cts)))
                {
                    var safe = MakeSafeName(typeName);
                    if (type.IsReferenceType)
                    {
                        sb.AppendLine($"                if (reader.TokenType == JsonTokenType.Null)");
                        sb.AppendLine("                {");
                        sb.AppendLine($"                    __val_{propName} = default;");
                        sb.AppendLine("                }");
                        sb.AppendLine("                else");
                        sb.AppendLine("                {");
                    }
                    sb.AppendLine($"                __val_{propName} = new {safe}_Converter().Read(ref reader, typeof({typeName}), options);");
                    if (type.IsReferenceType)
                    {
                        sb.AppendLine("                }");
                    }
                }
                else
                {
                    sb.AppendLine($"                throw new NotSupportedException(\"Property type not supported: {typeName}\");");
                }
                break;
        }
    }

    private enum PrimitiveKind { None, String, Bool, Int32, Int64 }

    private static PrimitiveKind GetPrimitiveKind(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_String) return PrimitiveKind.String;
        if (type.SpecialType == SpecialType.System_Boolean) return PrimitiveKind.Bool;
        if (type.SpecialType == SpecialType.System_Int32) return PrimitiveKind.Int32;
        if (type.SpecialType == SpecialType.System_Int64) return PrimitiveKind.Int64;
        return PrimitiveKind.None;
    }

    private static string GetTypeDisplayName(ITypeSymbol type)
    {
        return type switch
        {
            INamedTypeSymbol nts => ToFullyQualifiedName(nts),
            IArrayTypeSymbol ats => GetTypeDisplayName(ats.ElementType) + "[]",
            _ => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
        };
    }

    private static bool IsSupportedType(ITypeSymbol type, HashSet<string> known)
    {
        if (GetPrimitiveKind(type) != PrimitiveKind.None) return true;
        if (type is INamedTypeSymbol nts && nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            return IsSupportedType(nts.TypeArguments[0], known);
        }
        if (type is INamedTypeSymbol n && known.Contains(ToFullyQualifiedName(n))) return true;
        return false;
    }

    private static bool IsNullable(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol nts)
        {
            if (nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                return true;
        }
        return false;
    }

    private static string GetNullableUnderlying(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol nts && nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            var underlying = nts.TypeArguments[0];
            return GetTypeDisplayName(underlying);
        }
        return GetTypeDisplayName(type);
    }

    private static string ToCamelCase(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        if (char.IsLower(s[0])) return s;
        var chars = s.ToCharArray();
        chars[0] = char.ToLowerInvariant(chars[0]);
        return new string(chars);
    }

    private static string? GetJsonPropertyNameAttributeValue(IPropertySymbol prop)
    {
        foreach (var a in prop.GetAttributes())
        {
            var attrClass = a.AttributeClass;
            if (attrClass is null) continue;
            if (attrClass.ToDisplayString() == "System.Text.Json.Serialization.JsonPropertyNameAttribute")
            {
                if (a.ConstructorArguments.Length == 1)
                {
                    var v = a.ConstructorArguments[0];
                    if (v.Type?.SpecialType == SpecialType.System_String && v.Value is string s)
                        return s;
                }
            }
        }
        return null;
    }

    private static string EscapeStringLiteral(string s)
    {
        var sb = new StringBuilder();
        sb.Append('"');
        foreach (var ch in s)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\b': sb.Append("\\b"); break;
                case '\f': sb.Append("\\f"); break;
                default:
                    if (char.IsControl(ch))
                    {
                        sb.Append("\\u");
                        sb.Append(((int)ch).ToString("x4"));
                    }
                    else
                    {
                        sb.Append(ch);
                    }
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
